

const datos = [
    {
        iso_code: "AFG",
        country: "Afghanistan",
        year: 1990,
        urban_improved_total: "-",
        urban_improved_piped: 3,
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: 0,
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: "-",
        total_improved_piped: 1,
        total_improved_other: "-",
        total_unimproved_other: "-",
        total_unimproved_surface: "-"
    },
    {
        iso_code: "AFG",
        country: "Afghanistan",
        year: 2015,
        urban_improved_total: 78,
        urban_improved_piped: 31,
        urban_improved_other: 47,
        urban_unimproved_other: 20,
        rural_improved_total: 2,
        rural_improved_piped: 47,
        rural_improved_other: 5,
        rural_unimproved_other: 42,
        rural_unimproved_surface: 46,
        total_improved_total: 7,
        total_improved_piped: 55,
        total_improved_other: 12,
        total_unimproved_other: 43,
        total_unimproved_surface: 39
    },
    {
        iso_code: "ALB",
        country: "Albania",
        year: 1990,
        urban_improved_total: 100,
        urban_improved_piped: 98,
        urban_improved_other: 2,
        urban_unimproved_other: 0,
        rural_improved_total: 0,
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: "-",
        total_improved_piped: "-",
        total_improved_other: "-",
        total_unimproved_other: "-",
        total_unimproved_surface: "-"
    },
    {
        iso_code: "ALB",
        country: "Albania",
        year: 2015,
        urban_improved_total: 95,
        urban_improved_piped: 86,
        urban_improved_other: 9,
        urban_unimproved_other: 5,
        rural_improved_total: 0,
        rural_improved_piped: 95,
        rural_improved_other: 76,
        rural_unimproved_other: 19,
        rural_unimproved_surface: 5,
        total_improved_total: 0,
        total_improved_piped: 95,
        total_improved_other: 82,
        total_unimproved_other: 13,
        total_unimproved_surface: 5
    },
    {
        iso_code: "DZA",
        country: "Algeria",
        year: 1990,
        urban_improved_total: 97,
        urban_improved_piped: 87,
        urban_improved_other: 10,
        urban_unimproved_other: 3,
        rural_improved_total: 0,
        rural_improved_piped: 85,
        rural_improved_other: 47,
        rural_unimproved_other: 38,
        rural_unimproved_surface: 13,
        total_improved_total: 2,
        total_improved_piped: 91,
        total_improved_other: 67,
        total_unimproved_other: 24,
        total_unimproved_surface: 8
    },
    {
        iso_code: "DZA",
        country: "Algeria",
        year: 2015,
        urban_improved_total: 84,
        urban_improved_piped: 82,
        urban_improved_other: 2,
        urban_unimproved_other: 16,
        rural_improved_total: 0,
        rural_improved_piped: 82,
        rural_improved_other: 64,
        rural_unimproved_other: 18,
        rural_unimproved_surface: 18,
        total_improved_total: 0,
        total_improved_piped: 84,
        total_improved_other: 77,
        total_unimproved_other: 7,
        total_unimproved_surface: 16
    },
    {
        iso_code: "ASM",
        country: "American Samoa",
        year: 1990,
        urban_improved_total: "-",
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: 94,
        total_improved_piped: 65,
        total_improved_other: 29,
        total_unimproved_other: 6,
        total_unimproved_surface: "-"
    },
    {
        iso_code: "ASM",
        country: "American Samoa",
        year: 2015,
        urban_improved_total: "-",
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: 100,
        total_improved_piped: 92,
        total_improved_other: 8,
        total_unimproved_other: 0,
        total_unimproved_surface: 0
    },
    {
        iso_code: "AND",
        country: "Andorra",
        year: 1990,
        urban_improved_total: 100,
        urban_improved_piped: 100,
        urban_improved_other: 0,
        urban_unimproved_other: 0,
        rural_improved_total: 0,
        rural_improved_piped: 100,
        rural_improved_other: 100,
        rural_unimproved_other: 0,
        rural_unimproved_surface: 0,
        total_improved_total: 100,
        total_improved_piped: 100,
        total_improved_other: 100,
        total_unimproved_other: 0,
        total_unimproved_surface: 0
    },
    {
        iso_code: "AND",
        country: "Andorra",
        year: 2015,
        urban_improved_total: 100,
        urban_improved_piped: 100,
        urban_improved_other: 0,
        urban_unimproved_other: 0,
        rural_improved_total: 0,
        rural_improved_piped: 100,
        rural_improved_other: 100,
        rural_unimproved_other: 0,
        rural_unimproved_surface: 0,
        total_improved_total: 100,
        total_improved_piped: 100,
        total_improved_other: 100,
        total_unimproved_other: 0,
        total_unimproved_surface: 0
    },
    {
        iso_code: "AGO",
        country: "Angola",
        year: 1990,
        urban_improved_total: 52,
        urban_improved_piped: 19,
        urban_improved_other: 33,
        urban_unimproved_other: 44,
        rural_improved_total: 4,
        rural_improved_piped: 44,
        rural_improved_other: 1,
        rural_unimproved_other: 43,
        rural_unimproved_surface: 26,
        total_improved_total: 30,
        total_improved_piped: 46,
        total_improved_other: 5,
        total_unimproved_other: 41,
        total_unimproved_surface: 30
    },
    {
        iso_code: "AGO",
        country: "Angola",
        year: 2015,
        urban_improved_total: 75,
        urban_improved_piped: 32,
        urban_improved_other: 43,
        urban_unimproved_other: 21,
        rural_improved_total: 4,
        rural_improved_piped: 28,
        rural_improved_other: 2,
        rural_unimproved_other: 26,
        rural_unimproved_surface: 21,
        total_improved_total: 51,
        total_improved_piped: 49,
        total_improved_other: 15,
        total_unimproved_other: 34,
        total_unimproved_surface: 20
    },
    {
        iso_code: "AIA",
        country: "Anguilla",
        year: 1990,
        urban_improved_total: "-",
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: "-",
        total_improved_piped: "-",
        total_improved_other: "-",
        total_unimproved_other: "-",
        total_unimproved_surface: "-"
    },
    {
        iso_code: "AIA",
        country: "Anguilla",
        year: 2015,
        urban_improved_total: 95,
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: 5,
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: 95,
        total_improved_piped: "-",
        total_improved_other: "-",
        total_unimproved_other: 5,
        total_unimproved_surface: "-"
    },
    {
        iso_code: "ATG",
        country: "Antigua and Barbuda",
        year: 1990,
        urban_improved_total: "-",
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: 97,
        total_improved_piped: 61,
        total_improved_other: 36,
        total_unimproved_other: 3,
        total_unimproved_surface: "-"
    },
    {
        iso_code: "ATG",
        country: "Antigua and Barbuda",
        year: 2015,
        urban_improved_total: "-",
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: 98,
        total_improved_piped: "-",
        total_improved_other: "-",
        total_unimproved_other: 2,
        total_unimproved_surface: "-"
    },
    {
        iso_code: "ARG",
        country: "Argentina",
        year: 1990,
        urban_improved_total: 98,
        urban_improved_piped: 94,
        urban_improved_other: 4,
        urban_unimproved_other: 2,
        rural_improved_total: 0,
        rural_improved_piped: 69,
        rural_improved_other: 41,
        rural_unimproved_other: 28,
        rural_unimproved_surface: 19,
        total_improved_total: 12,
        total_improved_piped: 94,
        total_improved_other: 87,
        total_unimproved_other: 7,
        total_unimproved_surface: 4
    },
    {
        iso_code: "ARG",
        country: "Argentina",
        year: 2015,
        urban_improved_total: "-",
        urban_improved_piped: "-",
        urban_improved_other: "-",
        urban_unimproved_other: "-",
        rural_improved_total: "-",
        rural_improved_piped: "-",
        rural_improved_other: "-",
        rural_unimproved_other: "-",
        rural_unimproved_surface: "-",
        total_improved_total: "-",
        total_improved_piped: "-",
        total_improved_other: "-",
        total_unimproved_other: "-",
        total_unimproved_surface: "-"
    }
];

console.log(datos);

// Función para calcular la media de los valores de un campo numérico para un determinado valor en el campo de información geográfica
function calcularMediaCampo(country, caracteristica) {
    // Filtrar los datos para obtener solo las filas correspondientes a la ciudad especificada
    const datosCiudad = datos.filter(dato => dato.country === country);
    
    // Usar map para extraer los valores del campo específico y luego calcular la suma
    const suma = datosCiudad.map(dato => dato[caracteristica]).reduce((acumulador, valor) => acumulador + valor, 0);
    
    // Calcular la media
    const media = suma / datosCiudad.length;
    
    return media;
}


// Calcular y mostrar la media
datos.forEach(element => {
    const media = calcularMediaCampo(element.country, "total_improved_total");
    console.log(`La media de mejora total de ${element.country} es: ${media}`);
});