const API_BASE_JMS = "/api/v2/airbnb-listings";

let initialData = [
  {
    "name": "Appartement lumineux rue de Levis",
    "host_since": "25/02/2014",
    "host_location": "France",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.16,
    "host_acceptance_rate": 0.38,
    "neighbourhood": "Batignolles-Monceau",
    "city": "Paris",
    "latitude": 48.88418,
    "longitude": 2.31163,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Heating",
      "TV",
      "Kitchen",
      "Washer",
      "Dryer",
      "Wifi",
      "Long term stays allowed"
    ],
    "price": 90,
    "minimum_nights_number": 7,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Appartement Paris 19 - Balcon et vue sur Paris",
    "host_since": "30/11/2012",
    "host_location": "France",
    "host_response_time": "within a day",
    "host_response_rate": 0.09,
    "host_acceptance_rate": 0.19,
    "neighbourhood": "Buttes-Chaumont",
    "city": "Paris",
    "latitude": 48.87769,
    "longitude": 2.37268,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Heating",
      "TV",
      "Iron",
      "Kitchen",
      "Essentials",
      "Hair dryer",
      "Washer",
      "Bed linens",
      "Carbon monoxide alarm",
      "Hot water",
      "Smoke alarm",
      "Wifi",
      "Elevator",
      "Long term stays allowed",
      "Dedicated workspace"
    ],
    "price": 80,
    "minimum_nights_number": 10,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Paris 15",
    "host_since": "17/11/2017",
    "host_location": "Lebanon",
    "host_response_time": "within a day",
    "host_response_rate": 0.12,
    "host_acceptance_rate": 0.64,
    "neighbourhood": "Vaugirard",
    "city": "Paris",
    "latitude": 48.84355,
    "longitude": 2.28782,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Iron",
      "Shampoo",
      "Heating",
      "Washer",
      "Hair dryer",
      "Elevator",
      "Wifi",
      "Kitchen",
      "Essentials",
      "Hangers",
      "Long term stays allowed",
      "TV",
      "Breakfast"
    ],
    "price": 120,
    "minimum_nights_number": 5,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Bright and Charming Flat for 2 in Great Location",
    "host_since": "11/03/2020",
    "host_location": "Malaysia",
    "host_response_time": "within an hour",
    "host_response_rate": 0.45,
    "host_acceptance_rate": 0.93,
    "neighbourhood": "Reuilly",
    "city": "Paris",
    "latitude": 48.83679,
    "longitude": 2.39888,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Paid parking off premises",
      "Shampoo",
      "Dishes and silverware",
      "TV",
      "Kitchen",
      "Essentials",
      "Hair dryer",
      "Coffee maker",
      "Bed linens",
      "Refrigerator",
      "Hot water",
      "Hangers",
      "Wifi",
      "Cooking basics",
      "Elevator",
      "Long term stays allowed"
    ],
    "price": 83,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Amazing apartment - 4P/1BR - Canal Saint Martin",
    "host_since": "21/04/2020",
    "host_location": "France",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.2,
    "host_acceptance_rate": 0.96,
    "neighbourhood": "Enclos-St-Laurent",
    "city": "Paris",
    "latitude": 48.87406,
    "longitude": 2.37112,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Dishwasher",
      "Essentials",
      "Hot water",
      "Hangers",
      "Smoke alarm",
      "Wifi",
      "Long term stays allowed",
      "Dedicated workspace",
      "TV",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Private entrance",
      "Heating",
      "Kitchen",
      "Hair dryer",
      "Coffee maker",
      "Washer",
      "Microwave",
      "Cooking basics",
      "Shampoo",
      "Shower gel",
      "Bed linens",
      "Carbon monoxide alarm"
    ],
    "price": 105,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Superb studio close to Montmartre",
    "host_since": "23/09/2020",
    "host_location": "France",
    "host_response_time": "within a day",
    "host_response_rate": 0.23,
    "host_acceptance_rate": 0.33,
    "neighbourhood": "Buttes-Montmartre",
    "city": "Paris",
    "latitude": 48.89405,
    "longitude": 2.34785,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Heating",
      "TV",
      "Essentials",
      "Smoke alarm",
      "Wifi",
      "Long term stays allowed"
    ],
    "price": 56,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Designer Apartment in Batignolles",
    "host_since": "12/07/2019",
    "host_location": "France",
    "host_response_time": "within an hour",
    "host_response_rate": 0.43,
    "host_acceptance_rate": 0.11,
    "neighbourhood": "Batignolles-Monceau",
    "city": "Paris",
    "latitude": 48.88682,
    "longitude": 2.3116,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Dishwasher",
      "Essentials",
      "Hangers",
      "Smoke alarm",
      "Wifi",
      "Long term stays allowed",
      "Dedicated workspace",
      "TV",
      "Iron",
      "Dryer",
      "Refrigerator",
      "Oven",
      "Dishes and silverware",
      "Heating",
      "Kitchen",
      "Hair dryer",
      "Coffee maker",
      "Washer",
      "Microwave",
      "Cooking basics",
      "Shampoo",
      "Bed linens",
      "Carbon monoxide alarm",
      "Elevator"
    ],
    "price": 95,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Bright 1-BDR apartment centrally located",
    "host_since": "17/10/2014",
    "host_location": "Canada",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.9,
    "host_acceptance_rate": 0.3,
    "neighbourhood": "Enclos-St-Laurent",
    "city": "Paris",
    "latitude": 48.87197,
    "longitude": 2.35209,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Iron",
      "Shampoo",
      "Heating",
      "Washer",
      "Dedicated workspace",
      "Smoke alarm",
      "Wifi",
      "Kitchen",
      "Essentials",
      "Long term stays allowed"
    ],
    "price": 50,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Opera/Haussmann: Luxueux appartement d'architecte",
    "host_since": "19/01/2021",
    "host_location": "France",
    "host_response_time": "within an hour",
    "host_response_rate": 0.52,
    "host_acceptance_rate": 0.87,
    "neighbourhood": "Opera",
    "city": "Paris",
    "latitude": 48.87302,
    "longitude": 2.33444,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Shampoo",
      "Heating",
      "Lockbox",
      "Iron",
      "Kitchen",
      "Hair dryer",
      "Essentials",
      "Washer",
      "Dryer",
      "Air conditioning",
      "Hot water",
      "Hangers",
      "Smoke alarm",
      "Wifi",
      "Cooking basics",
      "Long term stays allowed",
      "Dedicated workspace"
    ],
    "price": 152,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Appartement 2 piÇŸ¶ùces proche canal st martin /Gare",
    "host_since": "27/09/2016",
    "host_location": "France",
    "host_response_time": "within an hour",
    "host_response_rate": 0.69,
    "host_acceptance_rate": 0.7,
    "neighbourhood": "Enclos-St-Laurent",
    "city": "Paris",
    "latitude": 48.87854,
    "longitude": 2.36212,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Private entrance",
      "Shampoo",
      "Heating",
      "TV",
      "Iron",
      "Lockbox",
      "Kitchen",
      "Hair dryer",
      "Essentials",
      "Washer",
      "Carbon monoxide alarm",
      "Hot water",
      "Hangers",
      "Smoke alarm",
      "Free parking on premises",
      "Wifi",
      "Long term stays allowed",
      "Dedicated workspace"
    ],
    "price": 75,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Wonderful apartment \"Porte de Versailles",
    "host_since": "03/02/2017",
    "host_location": "Switzerland",
    "host_response_time": "within an hour",
    "host_response_rate": 0.96,
    "host_acceptance_rate": 0.81,
    "neighbourhood": "Observatoire",
    "city": "Paris",
    "latitude": 48.83254,
    "longitude": 2.31738,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Essentials",
      "Hangers",
      "Smoke alarm",
      "Wifi",
      "Crib",
      "Long term stays allowed",
      "Dedicated workspace",
      "High chair",
      "TV",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Heating",
      "Kitchen",
      "Hair dryer",
      "Coffee maker",
      "Washer",
      "Microwave",
      "Cooking basics",
      "Shampoo",
      "Bed linens",
      "Carbon monoxide alarm"
    ],
    "price": 43,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Wonderful apartment near the piramids",
    "host_since": "03/02/2021",
    "host_location": "Egypt",
    "host_response_time": "within an hour",
    "host_response_rate": 0.93,
    "host_acceptance_rate": 0.91,
    "neighbourhood": "Nile River",
    "city": "Nile",
    "latitude": -43.2333,
    "longitude": 23.3178,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 2,
    "amenities_list": [
      "Essentials",
      "Hangers",
      "Smoke alarm",
      "Wifi",
      "Crib",
      "Long term stays allowed",
      "Dedicated workspace",
      "High chair",
      "TV",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Heating",
      "Kitchen",
      "Hair dryer",
      "Coffee maker",
      "Washer",
      "Microwave",
      "Cooking basics",
      "Shampoo",
      "Bed linens",
      "Carbon monoxide alarm"
    ],
    "price": 79,
    "minimum_nights_number": 1,
    "maximum_nights_number": 14,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Park Facing, Spacious 1 BR APT",
    "host_since": "06/11/2012",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.53,
    "host_acceptance_rate": 0.24,
    "neighbourhood": "Crown Heights",
    "city": "New York",
    "latitude": 40.66542,
    "longitude": -73.96062,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Smoke alarm",
      "Essentials",
      "Washer",
      "Dryer",
      "Shampoo",
      "Heating",
      "Wifi",
      "Elevator",
      "Long term stays allowed",
      "Carbon monoxide alarm",
      "Kitchen"
    ],
    "price": 110,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "DESIGNER DOWNTOWN 1 BEDROOM",
    "host_since": "01/07/2013",
    "host_location": "United States",
    "host_response_time": "within a day",
    "host_response_rate": 0.52,
    "host_acceptance_rate": 0.58,
    "neighbourhood": "East Village",
    "city": "New York",
    "latitude": 40.72232,
    "longitude": -73.98513,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Refrigerator",
      "Shampoo",
      "Air conditioning",
      "Baking sheet",
      "Kitchen",
      "Coffee maker",
      "Oven",
      "Iron",
      "Hangers",
      "Smoke alarm",
      "Washer",
      "Dedicated workspace",
      "Dryer",
      "Shower gel",
      "Hot water",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Hair dryer",
      "Bed linens",
      "Essentials",
      "Dishes and silverware",
      "TV",
      "Wifi",
      "Cable TV",
      "Heating",
      "Patio or balcony",
      "Cooking basics",
      "Stove",
      "Carbon monoxide alarm"
    ],
    "price": 179,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Sunny Brown Stone Apartment",
    "host_since": "05/03/2015",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.91,
    "host_acceptance_rate": 0.8,
    "neighbourhood": "Clinton Hill",
    "city": "New York",
    "latitude": 40.68308,
    "longitude": -73.96547,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Iron",
      "Essentials",
      "Smoke alarm",
      "TV",
      "Host greets you",
      "Wifi",
      "Shampoo",
      "Heating",
      "Air conditioning",
      "Long term stays allowed",
      "Kitchen"
    ],
    "price": 85,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Perfect retreat for a working professional",
    "host_since": "03/07/2015",
    "host_location": "United States",
    "host_response_time": "within a day",
    "host_response_rate": 0.81,
    "host_acceptance_rate": 0.18,
    "neighbourhood": "Sheepshead Bay",
    "city": "New York",
    "latitude": 40.58551,
    "longitude": -73.94439,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 1,
    "bedroom_number": 1,
    "amenities_list": [
      "Extra pillows and blankets",
      "Hair dryer",
      "Bed linens",
      "Iron",
      "Hangers",
      "Essentials",
      "Washer",
      "TV",
      "Smoke alarm",
      "Dryer",
      "Dedicated workspace",
      "Heating",
      "Wifi",
      "Dishes and silverware",
      "Private entrance",
      "Hot water",
      "Air conditioning",
      "Long term stays allowed",
      "Kitchen",
      "Cooking basics"
    ],
    "price": 120,
    "minimum_nights_number": 60,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Beautiful clean Gramercy 1bd room! Brand new!",
    "host_since": "03/08/2015",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.56,
    "host_acceptance_rate": 0.57,
    "neighbourhood": "Kips Bay",
    "city": "New York",
    "latitude": 40.73946,
    "longitude": -73.97997,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "First aid kit",
      "Hair dryer",
      "Iron",
      "Essentials",
      "Hangers",
      "Washer",
      "TV",
      "Smoke alarm",
      "Dryer",
      "Shampoo",
      "Heating",
      "Fire extinguisher",
      "Dedicated workspace",
      "Wifi",
      "Hot water",
      "Air conditioning",
      "Long term stays allowed",
      "Carbon monoxide alarm",
      "Kitchen"
    ],
    "price": 125,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Spacious studio with walk-in in closet",
    "host_since": "08/03/2019",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.45,
    "host_acceptance_rate": 0.37,
    "neighbourhood": "Chelsea",
    "city": "New York",
    "latitude": 40.73909,
    "longitude": -73.99882,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "First aid kit",
      "Hair dryer",
      "Iron",
      "Essentials",
      "Gym",
      "Washer",
      "Dedicated workspace",
      "TV",
      "Wifi",
      "Dryer",
      "Heating",
      "Shampoo",
      "Hangers",
      "Elevator",
      "Smoke alarm",
      "Air conditioning",
      "Hot water",
      "Long term stays allowed",
      "Carbon monoxide alarm",
      "Kitchen"
    ],
    "price": 245,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Garden condo w patio in New York artistic Bushwick",
    "host_since": "08/11/2019",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.58,
    "host_acceptance_rate": 0.08,
    "neighbourhood": "Bushwick",
    "city": "New York",
    "latitude": 40.69793,
    "longitude": -73.92801,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Nespresso machine",
      "Refrigerator",
      "Single level home",
      "Dining table",
      "Free street parking",
      "Washer – In building",
      "Kitchen",
      "Iron",
      "Hangers",
      "Dryer – In building",
      "Central air conditioning",
      "Smoke alarm",
      "Dedicated workspace",
      "Private fenced garden or backyard",
      "Fire extinguisher",
      "Shower gel",
      "Hot water",
      "40\" HDTV with Apple TV, Netflix, standard cable, Amazon Prime Video",
      "Cleaning products",
      "Long term stays allowed",
      "Shikai - natural plant based shampoo",
      "Extra pillows and blankets",
      "Hair dryer",
      "Bed linens",
      "Stainless steel gas stove",
      "Essentials",
      "Dishes and silverware",
      "Dishwasher",
      "Clothing storage: walk-in closet and dresser",
      "Puracy - natural plant based conditioner",
      "Cable TV",
      "Wifi – 300 Mbps",
      "Patio or balcony",
      "Cooking basics",
      "First aid kit",
      "Outdoor dining area",
      "Freezer",
      "Central heating",
      "Toaster",
      "Private entrance",
      "Puracy natural plant based body soap",
      "Laundromat nearby",
      "Stainless steel oven",
      "Outdoor furniture",
      "Wine glasses",
      "Carbon monoxide alarm"
    ],
    "price": 199,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "1 BR Apt, 1 block from Central Park, Heart of UWS",
    "host_since": "10/11/2013",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.7,
    "host_acceptance_rate": 0.5,
    "neighbourhood": "Upper West Side",
    "city": "New York",
    "latitude": 40.78298,
    "longitude": -73.97891,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Lockbox",
      "Smoke alarm",
      "Essentials",
      "Hangers",
      "Washer",
      "TV",
      "Dedicated workspace",
      "Dryer",
      "Shampoo",
      "Heating",
      "Wifi",
      "Dishes and silverware",
      "Air conditioning",
      "Long term stays allowed",
      "Carbon monoxide alarm",
      "Kitchen"
    ],
    "price": 200,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Studio on Park in Fort Greene, Brooklyn",
    "host_since": "29/07/2012",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.64,
    "host_acceptance_rate": 0.97,
    "neighbourhood": "Fort Greene",
    "city": "New York",
    "latitude": 40.68834,
    "longitude": -73.97417,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 1,
    "bedroom_number": 1,
    "amenities_list": [
      "Lockbox",
      "Smoke alarm",
      "Essentials",
      "Hangers",
      "Washer",
      "Dedicated workspace",
      "Wifi",
      "Dryer",
      "Heating",
      "Private entrance",
      "Air conditioning",
      "Long term stays allowed",
      "Kitchen"
    ],
    "price": 100,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Brooklyn Comfy & Luminous 2 rooms studio",
    "host_since": "03/06/2018",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.62,
    "host_acceptance_rate": 0.33,
    "neighbourhood": "Bushwick",
    "city": "New York",
    "latitude": 40.69941,
    "longitude": -73.92159,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Refrigerator",
      "Microwave",
      "Shampoo",
      "Air conditioning",
      "Free street parking",
      "Coffee maker",
      "Iron",
      "Hangers",
      "Smoke alarm",
      "Dedicated workspace",
      "Fire extinguisher",
      "Hot water",
      "Long term stays allowed",
      "Lockbox",
      "Hair dryer",
      "Essentials",
      "Dishes and silverware",
      "TV",
      "Wifi",
      "Heating",
      "Cooking basics",
      "First aid kit",
      "Private entrance",
      "Carbon monoxide alarm"
    ],
    "price": 120,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Bright and Stylish Atelier in New York City",
    "host_since": "23/08/2012",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.87,
    "host_acceptance_rate": 0.22,
    "neighbourhood": "Kips Bay",
    "city": "New York",
    "latitude": 40.73868,
    "longitude": -73.98037,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Breakfast",
      "Refrigerator",
      "Microwave",
      "Shampoo",
      "Air conditioning",
      "Kitchen",
      "Iron",
      "Hangers",
      "Smoke alarm",
      "Dedicated workspace",
      "Fire extinguisher",
      "Long term stays allowed",
      "Hair dryer",
      "Essentials",
      "Wifi",
      "Heating",
      "Stove",
      "Indoor fireplace",
      "Private entrance",
      "Laundromat nearby",
      "Carbon monoxide alarm"
    ],
    "price": 375,
    "minimum_nights_number": 4,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "One bedroom close to all",
    "host_since": "22/10/2019",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.91,
    "host_acceptance_rate": 0.16,
    "neighbourhood": "Midtown",
    "city": "New York",
    "latitude": 40.74301,
    "longitude": -73.98243,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Refrigerator",
      "Single level home",
      "Microwave",
      "Shampoo",
      "Air conditioning",
      "Bathtub",
      "Kitchen",
      "Coffee maker",
      "Oven",
      "Iron",
      "Hangers",
      "Smoke alarm",
      "Dedicated workspace",
      "Fire extinguisher",
      "Hot water",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Hair dryer",
      "Bed linens",
      "Essentials",
      "Dishes and silverware",
      "TV",
      "Wifi",
      "Cable TV",
      "Heating",
      "Paid parking off premises",
      "Cooking basics",
      "Stove",
      "Cleaning before checkout",
      "Window guards",
      "Carbon monoxide alarm",
      "Ethernet connection"
    ],
    "price": 109,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "1BR apt#2 in brownstone sleep 4. CLEAN CDC Req.",
    "host_since": "11/11/2013",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.74,
    "host_acceptance_rate": 0.15,
    "neighbourhood": "Bedford-Stuyvesant",
    "city": "New York",
    "latitude": 40.6819,
    "longitude": -73.94256,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Nespresso machine",
      "Refrigerator",
      "Shampoo",
      "Air conditioning",
      "Kitchen",
      "Oven",
      "Smoke alarm",
      "Hangers",
      "Fire extinguisher",
      "Shower gel",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Bed linens",
      "Essentials",
      "TV",
      "Wifi",
      "Heating",
      "Cooking basics",
      "Stove",
      "Luggage dropoff allowed",
      "Private entrance",
      "Conditioner",
      "Carbon monoxide alarm",
      "Pour-over coffee"
    ],
    "price": 95,
    "minimum_nights_number": 4,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Stay in style! Modern, vibrant, all new appliances",
    "host_since": "12/12/2014",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.98,
    "host_acceptance_rate": 0.25,
    "neighbourhood": "Gramercy",
    "city": "New York",
    "latitude": 40.73743,
    "longitude": -73.98832,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Heating",
      "TV",
      "Shampoo",
      "Essentials",
      "Long term stays allowed",
      "Iron",
      "Hangers",
      "Air conditioning",
      "Smoke alarm",
      "Carbon monoxide alarm",
      "Wifi",
      "Kitchen"
    ],
    "price": 110,
    "minimum_nights_number": 10,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Midtown West Furnished Luxury 1 Bed / 1 Bath Apt.",
    "host_since": "01/01/2020",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.44,
    "host_acceptance_rate": 0.48,
    "neighbourhood": "Hell's Kitchen",
    "city": "New York",
    "latitude": 40.76148,
    "longitude": -73.98765,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Refrigerator",
      "Microwave",
      "Air conditioning",
      "Free street parking",
      "Kitchen",
      "Coffee maker",
      "Oven",
      "Iron",
      "Hangers",
      "Smoke alarm",
      "Washer",
      "Dryer",
      "Hot water",
      "Long term stays allowed",
      "Paid parking on premises",
      "Extra pillows and blankets",
      "Hair dryer",
      "Bed linens",
      "Essentials",
      "Dishes and silverware",
      "Gym",
      "TV",
      "Dishwasher",
      "Wifi",
      "Cable TV",
      "Heating",
      "Cooking basics",
      "Stove",
      "Bread maker",
      "Private entrance",
      "Carbon monoxide alarm"
    ],
    "price": 135,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "1 bdr apt#3 in a renovated bright brownstone",
    "host_since": "11/11/2013",
    "host_location": "United States",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.56,
    "host_acceptance_rate": 0.3,
    "neighbourhood": "Bedford-Stuyvesant",
    "city": "New York",
    "latitude": 40.6821,
    "longitude": -73.94153,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Breakfast",
      "Smoke alarm",
      "Essentials",
      "Hangers",
      "TV",
      "Wifi",
      "Shampoo",
      "Heating",
      "Private entrance",
      "Fire extinguisher",
      "Air conditioning",
      "Long term stays allowed",
      "Carbon monoxide alarm",
      "Kitchen"
    ],
    "price": 88,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "The Renovated Midtown Apartment",
    "host_since": "28/02/2020",
    "host_location": "United States",
    "host_response_time": "within an hour",
    "host_response_rate": 0.52,
    "host_acceptance_rate": 0.15,
    "neighbourhood": "Midtown",
    "city": "New York",
    "latitude": 40.75563,
    "longitude": -73.96418,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "First aid kit",
      "Hair dryer",
      "Iron",
      "Hangers",
      "Essentials",
      "Washer",
      "TV",
      "Smoke alarm",
      "Dryer",
      "Fire extinguisher",
      "Heating",
      "Wifi",
      "Air conditioning",
      "Long term stays allowed",
      "Kitchen"
    ],
    "price": 130,
    "minimum_nights_number": 30,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Modern 1 BR apartment - 5 min walk from Nana BTS",
    "host_since": "01/11/2015",
    "host_location": "Thailand",
    "host_response_time": "within an hour",
    "host_response_rate": 0.82,
    "host_acceptance_rate": 0.11,
    "neighbourhood": "Vadhana",
    "city": "Bangkok",
    "latitude": 13.74449,
    "longitude": 100.55228,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Cable TV",
      "Air conditioning",
      "Dryer",
      "Dedicated workspace",
      "Elevator",
      "Fire extinguisher",
      "Iron",
      "TV",
      "Long term stays allowed",
      "Kitchen",
      "Shampoo",
      "Essentials",
      "Hair dryer",
      "Hangers",
      "Wifi"
    ],
    "price": 2900,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Oasis in Bangkok",
    "host_since": "08/07/2017",
    "host_location": "Thailand",
    "host_response_time": "within a day",
    "host_response_rate": 0.84,
    "host_acceptance_rate": 0.85,
    "neighbourhood": "Khlong Toei",
    "city": "Bangkok",
    "latitude": 13.72548,
    "longitude": 100.57391,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Air conditioning",
      "Patio or balcony",
      "Refrigerator",
      "Iron",
      "Oven",
      "Hair dryer",
      "Hangers",
      "Luggage dropoff allowed",
      "Cooking basics",
      "Hot water",
      "TV",
      "Smoke alarm",
      "Long term stays allowed",
      "Gym",
      "Carbon monoxide alarm",
      "Wifi",
      "Stove",
      "Free parking on premises",
      "Coffee maker",
      "Shampoo",
      "Essentials",
      "First aid kit",
      "Dryer",
      "Pool",
      "Dedicated workspace",
      "Elevator",
      "Microwave",
      "Host greets you",
      "Kitchen",
      "Washer"
    ],
    "price": 1300,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Hong Kong big house",
    "host_since": "16/01/2019",
    "host_location": "Hong Kong",
    "host_response_time": "within an hour",
    "host_response_rate": 0.06,
    "host_acceptance_rate": 0.32,
    "neighbourhood": "Eastern",
    "city": "Hong Kong",
    "latitude": 22.28309,
    "longitude": 114.21208,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Shampoo",
      "Long term stays allowed",
      "Dedicated workspace",
      "Private entrance",
      "Hot water",
      "Host greets you",
      "Washer",
      "TV",
      "Air conditioning",
      "Wifi",
      "Hangers",
      "Kitchen",
      "Essentials",
      "Elevator"
    ],
    "price": 414,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Small apartment near the river",
    "host_since": "20/04/2017",
    "host_location": "Hong Kong",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.88,
    "host_acceptance_rate": 0.39,
    "neighbourhood": "Sham Shui Po",
    "city": "Hong Kong",
    "latitude": 22.33605,
    "longitude": 114.13714,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Shampoo",
      "Hair dryer",
      "Long term stays allowed",
      "Dedicated workspace",
      "Private entrance",
      "Washer",
      "Iron",
      "TV",
      "Air conditioning",
      "Wifi",
      "Hangers",
      "Kitchen",
      "Essentials"
    ],
    "price": 340,
    "minimum_nights_number": 14,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Modern flat in the heart of Wan Chai",
    "host_since": "24/10/2014",
    "host_location": "Hong Kong",
    "host_response_time": "within a day",
    "host_response_rate": 0.08,
    "host_acceptance_rate": 0.62,
    "neighbourhood": "Wan Chai",
    "city": "Hong Kong",
    "latitude": 22.27559,
    "longitude": 114.17101,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Gym",
      "Shampoo",
      "Long term stays allowed",
      "Heating",
      "Washer",
      "43\" HDTV with standard cable",
      "Air conditioning",
      "Essentials",
      "Hangers",
      "Smoke alarm",
      "Wifi",
      "Kitchen",
      "Clothing storage: closet and walk-in closet",
      "Shower gel",
      "Cable TV"
    ],
    "price": 960,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Great location just 30 meters from cibeles.",
    "host_since": "11/06/2018",
    "host_location": "Mexico",
    "host_response_time": "within an hour",
    "host_response_rate": 0.18,
    "host_acceptance_rate": 0.18,
    "neighbourhood": "Cuauhtemoc",
    "city": "Mexico City",
    "latitude": 19.42008,
    "longitude": -99.16758,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Dedicated workspace",
      "Shampoo",
      "Essentials",
      "Cooking basics",
      "Hair dryer",
      "Kitchen",
      "Iron",
      "Hangers",
      "Dryer",
      "Wifi",
      "Hot water",
      "Long term stays allowed"
    ],
    "price": 657,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Gran Oportunidad en Polanco",
    "host_since": "28/11/2014",
    "host_location": "Switzerland",
    "host_response_time": "within a day",
    "host_response_rate": 0.14,
    "host_acceptance_rate": 0.62,
    "neighbourhood": "Miguel Hidalgo",
    "city": "Mexico City",
    "latitude": 19.43191,
    "longitude": -99.19905,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "TV",
      "Shampoo",
      "Essentials",
      "Kitchen",
      "Iron",
      "Hangers",
      "Private entrance",
      "Wifi",
      "Long term stays allowed"
    ],
    "price": 1220,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Departamento completo, nice apartment",
    "host_since": "05/12/2019",
    "host_location": "Mexico",
    "host_response_time": "within an hour",
    "host_response_rate": 0.5,
    "host_acceptance_rate": 0.67,
    "neighbourhood": "Iztapalapa",
    "city": "Mexico City",
    "latitude": 19.37577,
    "longitude": -99.11482,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 5,
    "bedroom_number": 1,
    "amenities_list": [
      "TV",
      "Dedicated workspace",
      "Ceiling fan",
      "Sound system",
      "Free parking on premises",
      "Extra pillows and blankets",
      "Free street parking",
      "Essentials",
      "Kitchen",
      "Refrigerator",
      "Wifi",
      "Long term stays allowed",
      "Portable fans",
      "Stove",
      "Dishes and silverware",
      "Private entrance",
      "Freezer",
      "Hot water",
      "Microwave",
      "Laundromat nearby",
      "Bed linens",
      "Iron",
      "Hangers"
    ],
    "price": 540,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Depa completo y a pasos de la plaza Santa Fe",
    "host_since": "06/08/2020",
    "host_location": "Mexico",
    "host_response_time": "within an hour",
    "host_response_rate": 0.3,
    "host_acceptance_rate": 0.01,
    "neighbourhood": "Cuajimalpa de Morelos",
    "city": "Mexico City",
    "latitude": 19.35978,
    "longitude": -99.27757,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Long term stays allowed",
      "Heating",
      "TV",
      "Dedicated workspace",
      "Shampoo",
      "Essentials",
      "Hair dryer",
      "Smoke alarm",
      "Iron",
      "Hangers",
      "Fire extinguisher",
      "Private entrance",
      "Wifi",
      "Free parking on premises",
      "Air conditioning",
      "Gym"
    ],
    "price": 1650,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Acogedor estudio Colonia Asturias bien ubicado",
    "host_since": "04/05/2020",
    "host_location": "Mexico",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.62,
    "host_acceptance_rate": 0.93,
    "neighbourhood": "Iztacalco",
    "city": "Mexico City",
    "latitude": 19.40497,
    "longitude": -99.12144,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Mini fridge",
      "Free street parking",
      "Shampoo",
      "Essentials",
      "Kitchen",
      "Hangers",
      "Dishes and silverware",
      "Dryer",
      "Stove",
      "Wifi",
      "Private entrance",
      "Coffee maker",
      "Microwave",
      "Long term stays allowed"
    ],
    "price": 300,
    "minimum_nights_number": 4,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Artist Loft in the Heart of Condesa",
    "host_since": "16/07/2012",
    "host_location": "Canada",
    "host_response_time": "within an hour",
    "host_response_rate": 0,
    "host_acceptance_rate": 0.25,
    "neighbourhood": "Cuauhtemoc",
    "city": "Mexico City",
    "latitude": 19.41009,
    "longitude": -99.17093,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "TV",
      "Shampoo",
      "Essentials",
      "Elevator",
      "Hair dryer",
      "Kitchen",
      "Iron",
      "Hangers",
      "Dryer",
      "Private entrance",
      "Wifi",
      "Hot water",
      "Free parking on premises",
      "Long term stays allowed"
    ],
    "price": 1092,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Comfy 1 bedroom apartment",
    "host_since": "31/10/2014",
    "host_location": "Mexico",
    "host_response_time": "within an hour",
    "host_response_rate": 0.51,
    "host_acceptance_rate": 0.3,
    "neighbourhood": "Benito Juarez",
    "city": "Mexico City",
    "latitude": 19.39107,
    "longitude": -99.17944,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Conditioner",
      "TV",
      "Dedicated workspace",
      "Shower gel",
      "Luggage dropoff allowed",
      "Extra pillows and blankets",
      "Free parking on premises",
      "Body soap",
      "Paid street parking off premises",
      "Shampoo",
      "Essentials",
      "Room-darkening shades",
      "Cable TV",
      "Cooking basics",
      "Kitchen",
      "Refrigerator",
      "Wifi",
      "Long term stays allowed",
      "Oven",
      "Stainless steel electric stove",
      "First aid kit",
      "Dishes and silverware",
      "Coffee maker",
      "Hot water",
      "Microwave",
      "Laundromat nearby",
      "Bed linens",
      "Hair dryer",
      "Iron",
      "Hangers"
    ],
    "price": 609,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Suite amueblada",
    "host_since": "23/10/2016",
    "host_location": "Mexico",
    "host_response_time": "within an hour",
    "host_response_rate": 0.36,
    "host_acceptance_rate": 0.56,
    "neighbourhood": "Miguel Hidalgo",
    "city": "Mexico City",
    "latitude": 19.43155,
    "longitude": -99.18665,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "TV",
      "Dedicated workspace",
      "Essentials",
      "Hangers",
      "Wifi",
      "Long term stays allowed"
    ],
    "price": 800,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Estudio no coracao da Lapa!",
    "host_since": "22/02/2014",
    "host_location": "France",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.54,
    "host_acceptance_rate": 0.4,
    "neighbourhood": "Centro",
    "city": "Rio de Janeiro",
    "latitude": -22.91235,
    "longitude": -43.18332,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Elevator",
      "Kitchen",
      "Air conditioning",
      "Pool",
      "Long term stays allowed",
      "Gym",
      "Essentials",
      "Wifi",
      "Iron",
      "TV",
      "Hangers"
    ],
    "price": 140,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Apartamento Copacabana posto 6",
    "host_since": "22/12/2014",
    "host_location": "Brazil",
    "host_response_time": "within an hour",
    "host_response_rate": 0.92,
    "host_acceptance_rate": 0.84,
    "neighbourhood": "Copacabana",
    "city": "Rio de Janeiro",
    "latitude": -22.98137,
    "longitude": -43.19094,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Kitchen",
      "Air conditioning",
      "Long term stays allowed",
      "Essentials",
      "Wifi",
      "TV"
    ],
    "price": 145,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Aconchegante e no melhor lugar!!",
    "host_since": "29/12/2015",
    "host_location": "Brazil",
    "host_response_time": "within an hour",
    "host_response_rate": 0.47,
    "host_acceptance_rate": 0.66,
    "neighbourhood": "Barra da Tijuca",
    "city": "Rio de Janeiro",
    "latitude": -23.01097,
    "longitude": -43.32238,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 6,
    "bedroom_number": 1,
    "amenities_list": [
      "Smoke alarm",
      "Elevator",
      "Kitchen",
      "Air conditioning",
      "Pool",
      "Long term stays allowed",
      "Gym",
      "TV",
      "Free parking on premises"
    ],
    "price": 400,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "ACONCHEGANTE APARTAMENTO NA BARRA DA TIJUCA",
    "host_since": "22/02/2016",
    "host_location": "Brazil",
    "host_response_time": "within an hour",
    "host_response_rate": 0.44,
    "host_acceptance_rate": 0.03,
    "neighbourhood": "Jacarepagua",
    "city": "Rio de Janeiro",
    "latitude": -22.97194,
    "longitude": -43.358,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Elevator",
      "Dedicated workspace",
      "Kitchen",
      "Washer",
      "Hot water",
      "Air conditioning",
      "Pool",
      "Gym",
      "Essentials",
      "Long term stays allowed",
      "Dryer",
      "Iron",
      "TV",
      "Hangers",
      "Free street parking",
      "Patio or balcony",
      "Free parking on premises",
      "Cable TV"
    ],
    "price": 244,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Studio Boutique Modern",
    "host_since": "12/09/2020",
    "host_location": "Brazil",
    "host_response_time": "within an hour",
    "host_response_rate": 0.79,
    "host_acceptance_rate": 0.8,
    "neighbourhood": "Copacabana",
    "city": "Rio de Janeiro",
    "latitude": -22.98474,
    "longitude": -43.1907,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Air conditioning",
      "Essentials",
      "Freezer",
      "Hangers",
      "Single level home",
      "Coffee maker",
      "Dedicated workspace",
      "Bed linens",
      "Hot water",
      "Nespresso machine",
      "Ethernet connection",
      "Cleaning products",
      "Long term stays allowed",
      "Microwave",
      "Refrigerator",
      "Room-darkening shades",
      "Wifi",
      "Dishes and silverware",
      "Cooking basics",
      "Stove",
      "Lockbox",
      "Kitchen",
      "Drying rack for clothing",
      "Conditioner",
      "TV",
      "Shampoo"
    ],
    "price": 389,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Seu lar em Copacabana",
    "host_since": "24/02/2020",
    "host_location": "Brazil",
    "host_response_time": "within an hour",
    "host_response_rate": 0.67,
    "host_acceptance_rate": 0.97,
    "neighbourhood": "Copacabana",
    "city": "Rio de Janeiro",
    "latitude": -22.96368,
    "longitude": -43.17422,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Extra pillows and blankets",
      "Air conditioning",
      "Dining table",
      "Essentials",
      "Luggage dropoff allowed",
      "Paid parking off premises",
      "Freezer",
      "Clothing storage",
      "Hangers",
      "Smoke alarm",
      "Washer",
      "Bed linens",
      "Hot water",
      "Ethernet connection",
      "Long term stays allowed",
      "Microwave",
      "Refrigerator",
      "Room-darkening shades",
      "Wifi",
      "Dishes and silverware",
      "Cooking basics",
      "Stove",
      "Pocket wifi",
      "Lockbox",
      "Outdoor dining area",
      "Kitchen",
      "Ceiling fan",
      "Drying rack for clothing",
      "TV",
      "Oven",
      "Pour-over coffee"
    ],
    "price": 134,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Na beira da praia!",
    "host_since": "25/01/2017",
    "host_location": "Brazil",
    "host_response_time": "within an hour",
    "host_response_rate": 0.48,
    "host_acceptance_rate": 0.01,
    "neighbourhood": "Barra da Tijuca",
    "city": "Rio de Janeiro",
    "latitude": -23.00994,
    "longitude": -43.37146,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Wine glasses",
      "Extra pillows and blankets",
      "Air conditioning",
      "Dining table",
      "Gym",
      "Essentials",
      "Luggage dropoff allowed",
      "Freezer",
      "Sauna",
      "Clothing storage",
      "Hangers",
      "Coffee maker",
      "Dedicated workspace",
      "Washer",
      "Bed linens",
      "Hot water",
      "Waterfront",
      "Ethernet connection",
      "Cleaning products",
      "Long term stays allowed",
      "Microwave",
      "Refrigerator",
      "Wifi",
      "Dishes and silverware",
      "Beachfront",
      "Cooking basics",
      "Stove",
      "Hair dryer",
      "Free parking on premises",
      "Pocket wifi",
      "Elevator",
      "Outdoor dining area",
      "Kitchen",
      "Pool table",
      "Pool",
      "Drying rack for clothing",
      "TV",
      "Oven",
      "Ping pong table",
      "Fire extinguisher"
    ],
    "price": 299,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Modern, 1 bedroom apartment in Alexandria",
    "host_since": "14/07/2014",
    "host_location": "United Kingdom",
    "host_response_time": "within a day",
    "host_response_rate": 0.39,
    "host_acceptance_rate": 0.4,
    "neighbourhood": "Sydney",
    "city": "Sydney",
    "latitude": -33.90924,
    "longitude": 151.19844,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Iron",
      "Long term stays allowed",
      "Smoke alarm",
      "Air conditioning",
      "Dryer",
      "Free street parking",
      "Kitchen",
      "Hangers",
      "Elevator",
      "Wifi",
      "Carbon monoxide alarm",
      "TV",
      "Heating"
    ],
    "price": 80,
    "minimum_nights_number": 4,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Beautiful Garden Apartment 5 mins from Beach",
    "host_since": "12/03/2014",
    "host_location": "Australia",
    "host_response_time": "within an hour",
    "host_response_rate": 0.77,
    "host_acceptance_rate": 0.99,
    "neighbourhood": "Warringah",
    "city": "Sydney",
    "latitude": -33.77811,
    "longitude": 151.28066,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Iron",
      "Breakfast",
      "Long term stays allowed",
      "Private entrance",
      "Essentials",
      "Dedicated workspace",
      "Kitchen",
      "Hangers",
      "Shampoo",
      "Wifi",
      "Hair dryer",
      "Smoke alarm",
      "Fire extinguisher"
    ],
    "price": 195,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Cozy Place in Manly Beach",
    "host_since": "23/11/2014",
    "host_location": "France",
    "host_response_time": "within an hour",
    "host_response_rate": 0.62,
    "host_acceptance_rate": 0.54,
    "neighbourhood": "Manly",
    "city": "Sydney",
    "latitude": -33.79412,
    "longitude": 151.28514,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Long term stays allowed",
      "Hot water",
      "Dryer",
      "Essentials",
      "Kitchen",
      "Elevator",
      "Shampoo",
      "Wifi",
      "Hair dryer",
      "Smoke alarm",
      "Carbon monoxide alarm",
      "Heating"
    ],
    "price": 180,
    "minimum_nights_number": 4,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Entire Apartment With Iconic View",
    "host_since": "18/12/2018",
    "host_location": "Australia",
    "host_response_time": "within an hour",
    "host_response_rate": 0.35,
    "host_acceptance_rate": 0.05,
    "neighbourhood": "North Sydney",
    "city": "Sydney",
    "latitude": -33.84905,
    "longitude": 151.2171,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Iron",
      "Free parking on premises",
      "Smoke alarm",
      "Long term stays allowed",
      "Private entrance",
      "Dryer",
      "Essentials",
      "Dedicated workspace",
      "Kitchen",
      "Hangers",
      "Refrigerator",
      "Shampoo",
      "Wifi",
      "Hair dryer",
      "TV",
      "Heating"
    ],
    "price": 370,
    "minimum_nights_number": 10,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Sunny Suburban Paradise",
    "host_since": "12/09/2014",
    "host_location": "Australia",
    "host_response_time": "within an hour",
    "host_response_rate": 0.46,
    "host_acceptance_rate": 0.47,
    "neighbourhood": "Warringah",
    "city": "Sydney",
    "latitude": -33.7473,
    "longitude": 151.28867,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Free parking on premises",
      "Breakfast",
      "Long term stays allowed",
      "Private entrance",
      "Dryer",
      "Essentials",
      "Kitchen",
      "Wifi",
      "Smoke alarm"
    ],
    "price": 150,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Beautiful spacious apartment,10m walk to the beach",
    "host_since": "19/01/2021",
    "host_location": "Australia",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.77,
    "host_acceptance_rate": 0.12,
    "neighbourhood": "Randwick",
    "city": "Sydney",
    "latitude": -33.91899,
    "longitude": 151.24639,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Iron",
      "Clothing storage: dresser",
      "Smoke alarm",
      "Microwave",
      "Hot water kettle",
      "Free parking on premises",
      "Long term stays allowed",
      "Essentials",
      "Dedicated workspace",
      "Kitchen",
      "Oven",
      "Dining table",
      "Wifi",
      "Hair dryer",
      "TV",
      "Toaster",
      "Drying rack for clothing",
      "Fire extinguisher"
    ],
    "price": 100,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "BeÇ?÷iktaÇ?÷ catÇ?¶ñ katÇ?¶ñ Daire",
    "host_since": "05/05/2015",
    "host_location": "Turkey",
    "host_response_time": "within a day",
    "host_response_rate": 0.97,
    "host_acceptance_rate": 0.86,
    "neighbourhood": "Besiktas",
    "city": "Istanbul",
    "latitude": 41.04489,
    "longitude": 29.00538,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Hot water",
      "Dishwasher",
      "Essentials",
      "Paid parking off premises",
      "Luggage dropoff allowed",
      "Shampoo",
      "Cooking basics",
      "Wifi",
      "Hair dryer",
      "Cable TV",
      "TV",
      "Washer",
      "Free street parking",
      "Long term stays allowed",
      "Refrigerator",
      "Iron",
      "Air conditioning",
      "Cleaning before checkout",
      "Extra pillows and blankets",
      "Dedicated workspace",
      "Heating",
      "Patio or balcony",
      "Host greets you",
      "Ethernet connection",
      "Bed linens",
      "Kitchen",
      "Free parking on premises",
      "Dishes and silverware"
    ],
    "price": 180,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Cosy Apartment in Taksim",
    "host_since": "11/09/2019",
    "host_location": "Turkey",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.35,
    "host_acceptance_rate": 0.13,
    "neighbourhood": "Beyoglu",
    "city": "Istanbul",
    "latitude": 41.03782,
    "longitude": 28.97312,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Iron",
      "Hangers",
      "Wifi",
      "Essentials",
      "Heating",
      "Kitchen",
      "TV",
      "Hot water",
      "Long term stays allowed",
      "Hair dryer"
    ],
    "price": 150,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Modern Istanbul Apartment in BeyoÇ?÷lu",
    "host_since": "25/05/2019",
    "host_location": "Turkey",
    "host_response_time": "within an hour",
    "host_response_rate": 0.67,
    "host_acceptance_rate": 0.71,
    "neighbourhood": "Beyoglu",
    "city": "Istanbul",
    "latitude": 41.03431,
    "longitude": 28.99157,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Iron",
      "Dishwasher",
      "Essentials",
      "Bed linens",
      "Heating",
      "Kitchen",
      "Cooking basics",
      "Refrigerator",
      "Elevator",
      "Dryer",
      "Dedicated workspace",
      "Patio or balcony",
      "Ethernet connection",
      "Wifi",
      "Hot water",
      "Shampoo",
      "Hangers",
      "Breakfast",
      "Coffee maker",
      "TV",
      "Oven",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Hair dryer",
      "Pocket wifi"
    ],
    "price": 500,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Cozy flat with 2 big terraces in central Moda",
    "host_since": "13/01/2015",
    "host_location": "Turkey",
    "host_response_time": "within an hour",
    "host_response_rate": 0.88,
    "host_acceptance_rate": 0.91,
    "neighbourhood": "Kadikoy",
    "city": "Istanbul",
    "latitude": 40.98251,
    "longitude": 29.02473,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Cable TV",
      "Free street parking",
      "Washer",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Bed linens",
      "Hot water",
      "Kitchen",
      "Game console",
      "Refrigerator",
      "Ethernet connection",
      "Shower gel",
      "Dedicated workspace",
      "Patio or balcony",
      "Iron",
      "Coffee maker",
      "Stove",
      "Wifi",
      "Luggage dropoff allowed",
      "Dishes and silverware",
      "TV",
      "Heating",
      "Hair dryer",
      "Cooking basics",
      "Essentials",
      "Shampoo"
    ],
    "price": 407,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Khayyam Arch - A Central Nest in Beyoglu",
    "host_since": "26/07/2011",
    "host_location": "Turkey",
    "host_response_time": "within an hour",
    "host_response_rate": 0.7,
    "host_acceptance_rate": 0.22,
    "neighbourhood": "Beyoglu",
    "city": "Istanbul",
    "latitude": 41.03694,
    "longitude": 28.97591,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Hangers",
      "Laundromat nearby",
      "First aid kit",
      "Private entrance",
      "Carbon monoxide alarm",
      "Washer",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Bed linens",
      "Hot water",
      "Kitchen",
      "Portable fans",
      "Ethernet connection",
      "Dedicated workspace",
      "Iron",
      "Wifi",
      "Luggage dropoff allowed",
      "Fire extinguisher",
      "Dishes and silverware",
      "TV",
      "Heating",
      "Hair dryer",
      "Cooking basics",
      "Essentials",
      "Shampoo"
    ],
    "price": 333,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "LÇŸ?X REZÇ?¶øDENCE DELUX SUÇ?¶øT",
    "host_since": "25/05/2018",
    "host_location": "Turkey",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.51,
    "host_acceptance_rate": 0.25,
    "neighbourhood": "Besiktas",
    "city": "Istanbul",
    "latitude": 41.06627,
    "longitude": 29.00445,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Hangers",
      "Wifi",
      "Free street parking",
      "Breakfast",
      "Essentials",
      "Gym",
      "Hair dryer",
      "Air conditioning",
      "Free parking on premises",
      "Kitchen",
      "Cooking basics",
      "TV",
      "Long term stays allowed",
      "Dedicated workspace",
      "Refrigerator",
      "Dryer",
      "Shampoo"
    ],
    "price": 806,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Peaceful home in KadÇ?¶ñkÇŸ¶ôy, 10 minutes to everywhere",
    "host_since": "06/02/2017",
    "host_location": "Turkey",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.64,
    "host_acceptance_rate": 0.24,
    "neighbourhood": "Kadikoy",
    "city": "Istanbul",
    "latitude": 40.99455,
    "longitude": 29.03111,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Hangers",
      "Conditioner",
      "Dining table",
      "Cleaning products",
      "Toaster",
      "Washer",
      "Free street parking",
      "Long term stays allowed",
      "Paid parking lot off premises",
      "Extra pillows and blankets",
      "Dishwasher",
      "Hot water kettle",
      "Host greets you",
      "Bed linens",
      "Hot water",
      "Stainless steel oven",
      "Kitchen",
      "Bathtub",
      "Portable fans",
      "Body soap",
      "Freezer",
      "Baking sheet",
      "Air conditioning",
      "Shower gel",
      "Refrigerator",
      "Bikes",
      "Iron",
      "Clothing storage: dresser and closet",
      "Coffee maker",
      "Wifi",
      "Stove",
      "Luggage dropoff allowed",
      "Dishes and silverware",
      "Drying rack for clothing",
      "Shared garden or backyard",
      "Wine glasses",
      "Heating",
      "Hair dryer",
      "Cooking basics",
      "Essentials",
      "Safe",
      "Shampoo"
    ],
    "price": 119,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Luxurious Flat at the Heart of Bahcesehir",
    "host_since": "18/01/2021",
    "host_location": "Turkey",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.78,
    "host_acceptance_rate": 0.73,
    "neighbourhood": "Esenyurt",
    "city": "Istanbul",
    "latitude": 41.05788,
    "longitude": 28.66626,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Hangers",
      "Wifi",
      "Fire extinguisher",
      "Essentials",
      "Heating",
      "Gym",
      "Hair dryer",
      "Air conditioning",
      "Free parking on premises",
      "Hot tub",
      "Carbon monoxide alarm",
      "Kitchen",
      "TV",
      "Long term stays allowed",
      "Smoke alarm",
      "Dryer",
      "Shampoo"
    ],
    "price": 208,
    "minimum_nights_number": 60,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Cosy Room in central of the Istanbul near Galata",
    "host_since": "09/06/2019",
    "host_location": "Turkey",
    "host_response_time": "within an hour",
    "host_response_rate": 0.82,
    "host_acceptance_rate": 0.54,
    "neighbourhood": "Beyoglu",
    "city": "Istanbul",
    "latitude": 41.02474,
    "longitude": 28.97159,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Hangers",
      "First aid kit",
      "Fire extinguisher",
      "Air conditioning",
      "TV",
      "Hot water",
      "Hair dryer",
      "Wifi",
      "Iron",
      "Washer",
      "Long term stays allowed",
      "Essentials",
      "Shampoo"
    ],
    "price": 222,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Cosy Room inCentral of the Istanbul near Galata(2)",
    "host_since": "09/06/2019",
    "host_location": "Turkey",
    "host_response_time": "within an hour",
    "host_response_rate": 0.34,
    "host_acceptance_rate": 0.79,
    "neighbourhood": "Beyoglu",
    "city": "Istanbul",
    "latitude": 41.0252,
    "longitude": 28.97215,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Hangers",
      "First aid kit",
      "Fire extinguisher",
      "Air conditioning",
      "TV",
      "Hot water",
      "Hair dryer",
      "Wifi",
      "Iron",
      "Washer",
      "Long term stays allowed",
      "Essentials",
      "Shampoo"
    ],
    "price": 250,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Casa Selinunte",
    "host_since": "17/10/2017",
    "host_location": "Italy",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.62,
    "host_acceptance_rate": 0.5,
    "neighbourhood": "VII San Giovanni/Cinecitta",
    "city": "Rome",
    "latitude": 41.85646,
    "longitude": 12.55291,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Dishes and silverware",
      "Oven",
      "Washer",
      "TV",
      "Dedicated workspace",
      "Patio or balcony",
      "Cooking basics",
      "Single level home",
      "Wifi",
      "Essentials",
      "Hair dryer",
      "Stove",
      "Long term stays allowed",
      "Hangers",
      "Kitchen",
      "Refrigerator",
      "Heating"
    ],
    "price": 41,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "The Rica House",
    "host_since": "27/09/2019",
    "host_location": "Italy",
    "host_response_time": "within an hour",
    "host_response_rate": 0.76,
    "host_acceptance_rate": 0.13,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.87837,
    "longitude": 12.47061,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Dedicated workspace",
      "Microwave",
      "Fire extinguisher",
      "Hangers",
      "Refrigerator",
      "Dishes and silverware",
      "Wifi",
      "Stove",
      "Hair dryer",
      "Kitchen",
      "Heating",
      "TV",
      "Air conditioning",
      "Coffee maker",
      "Long term stays allowed",
      "Hot water",
      "Extra pillows and blankets",
      "Oven",
      "Essentials",
      "First aid kit"
    ],
    "price": 40,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Mansarda con Terrazzo vicina al Vaticano",
    "host_since": "09/12/2019",
    "host_location": "Italy",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.47,
    "host_acceptance_rate": 0.47,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.90765,
    "longitude": 12.46359,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Fire extinguisher",
      "Wifi",
      "Essentials",
      "Hangers",
      "Air conditioning",
      "Long term stays allowed",
      "Kitchen",
      "Heating"
    ],
    "price": 29,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "A quiet and cozy place in San Lorenzo",
    "host_since": "26/01/2014",
    "host_location": "Italy",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.31,
    "host_acceptance_rate": 0.44,
    "neighbourhood": "II Parioli/Nomentano",
    "city": "Rome",
    "latitude": 41.89563,
    "longitude": 12.51535,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "TV",
      "Dedicated workspace",
      "Private entrance",
      "Long term stays allowed",
      "Wifi",
      "Essentials",
      "Hair dryer",
      "Air conditioning",
      "Hangers",
      "Iron",
      "Kitchen",
      "Heating"
    ],
    "price": 85,
    "minimum_nights_number": 7,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Delightful,comfortable apartment, close to Vatican",
    "host_since": "26/10/2016",
    "host_location": "Italy",
    "host_response_time": "within a day",
    "host_response_rate": 0.49,
    "host_acceptance_rate": 0.11,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.90858,
    "longitude": 12.46096,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Dishwasher",
      "Paid parking off premises",
      "Pack ’n Play/travel crib",
      "Washer",
      "Dedicated workspace",
      "Window guards",
      "Microwave",
      "Fire extinguisher",
      "Hangers",
      "Iron",
      "Carbon monoxide alarm",
      "Ethernet connection",
      "Luggage dropoff allowed",
      "Refrigerator",
      "Building staff",
      "Dishes and silverware",
      "Private entrance",
      "Children’s dinnerware",
      "Bathtub",
      "Wifi",
      "Stove",
      "Hair dryer",
      "Cooking basics",
      "Babysitter recommendations",
      "Children’s books and toys",
      "Kitchen",
      "Garden or backyard",
      "High chair",
      "Fireplace guards",
      "TV",
      "Baby safety gates",
      "Smoke alarm",
      "Air conditioning",
      "Baby bath",
      "Coffee maker",
      "Hot water",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Shampoo",
      "Single level home",
      "Essentials",
      "First aid kit",
      "Bed linens",
      "Room-darkening shades"
    ],
    "price": 110,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Modern loft Testaccio",
    "host_since": "09/11/2013",
    "host_location": "Italy",
    "host_response_time": "within a day",
    "host_response_rate": 0.55,
    "host_acceptance_rate": 0.26,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.87989,
    "longitude": 12.47839,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Microwave",
      "Hangers",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Host greets you",
      "Cooking basics",
      "Wifi",
      "Stove",
      "Shower gel",
      "Hair dryer",
      "Kitchen",
      "Breakfast",
      "Heating",
      "Baking sheet",
      "TV",
      "Air conditioning",
      "Coffee maker",
      "Hot water",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Oven",
      "Elevator",
      "Shampoo",
      "Essentials",
      "Bed linens"
    ],
    "price": 60,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Via Mocenigo 20 Prati Terrace Apartment",
    "host_since": "13/03/2020",
    "host_location": "Italy",
    "host_response_time": "within an hour",
    "host_response_rate": 0.47,
    "host_acceptance_rate": 0,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.90838,
    "longitude": 12.45154,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Paid parking off premises",
      "Pack ’n Play/travel crib",
      "Lockbox",
      "Washer",
      "Dedicated workspace",
      "Microwave",
      "Fire extinguisher",
      "Hangers",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Cooking basics",
      "Wifi",
      "Stove",
      "Hair dryer",
      "Kitchen",
      "Heating",
      "Garden or backyard",
      "TV",
      "Patio or balcony",
      "Smoke alarm",
      "Air conditioning",
      "Coffee maker",
      "Hot water",
      "Long term stays allowed",
      "Extra pillows and blankets",
      "Oven",
      "Shampoo",
      "Bed linens",
      "Essentials",
      "First aid kit",
      "Carbon monoxide alarm"
    ],
    "price": 75,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  },
  {
    "name": "Gondar House A in zona Libia",
    "host_since": "04/04/2016",
    "host_location": "Italy",
    "host_response_time": "within a day",
    "host_response_rate": 0.22,
    "host_acceptance_rate": 0.09,
    "neighbourhood": "II Parioli/Nomentano",
    "city": "Rome",
    "latitude": 41.93428,
    "longitude": 12.5205,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Washer",
      "Hangers",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Cooking basics",
      "Wifi",
      "Stove",
      "Hair dryer",
      "Kitchen",
      "Heating",
      "Cleaning before checkout",
      "TV",
      "Air conditioning",
      "Hot water",
      "Long term stays allowed",
      "Free street parking",
      "Extra pillows and blankets",
      "Oven",
      "Elevator",
      "Essentials",
      "Paid parking on premises",
      "Bed linens"
    ],
    "price": 45,
    "minimum_nights_number": 10,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Casa monolocale Selinunte",
    "host_since": "17/10/2017",
    "host_location": "Italy",
    "host_response_time": "within a few hours",
    "host_response_rate": 0.52,
    "host_acceptance_rate": 0.27,
    "neighbourhood": "VII San Giovanni/Cinecitta",
    "city": "Rome",
    "latitude": 41.85693,
    "longitude": 12.55075,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Shampoo",
      "Washer",
      "Air conditioning",
      "Cooking basics",
      "Hangers",
      "Hair dryer",
      "Stove",
      "Patio or balcony",
      "TV",
      "Single level home",
      "Dishes and silverware",
      "Long term stays allowed",
      "Wifi",
      "Dedicated workspace",
      "Essentials",
      "Kitchen",
      "Refrigerator",
      "Heating",
      "Oven"
    ],
    "price": 38,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Luxury One Bedroom Apartment",
    "host_since": "11/11/2014",
    "host_location": "Italy",
    "host_response_time": "within a day",
    "host_response_rate": 0.68,
    "host_acceptance_rate": 0,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.8972,
    "longitude": 12.50239,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 4,
    "bedroom_number": 1,
    "amenities_list": [
      "Dishwasher",
      "Paid parking off premises",
      "Washer",
      "Microwave",
      "Fire extinguisher",
      "Hangers",
      "Iron",
      "Refrigerator",
      "Dishes and silverware",
      "Cooking basics",
      "Wifi",
      "Stove",
      "Hair dryer",
      "Babysitter recommendations",
      "Kitchen",
      "Heating",
      "Crib",
      "Air conditioning",
      "Coffee maker",
      "Long term stays allowed",
      "Single level home",
      "Essentials",
      "First aid kit",
      "Bed linens",
      "Room-darkening shades"
    ],
    "price": 200,
    "minimum_nights_number": 3,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Casa Aurora",
    "host_since": "29/11/2016",
    "host_location": "Italy",
    "host_response_time": "within an hour",
    "host_response_rate": 0.43,
    "host_acceptance_rate": 0.22,
    "neighbourhood": "XIII Aurelia",
    "city": "Rome",
    "latitude": 41.90327,
    "longitude": 12.44182,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 2,
    "bedroom_number": 1,
    "amenities_list": [
      "Shampoo",
      "Washer",
      "TV",
      "Long term stays allowed",
      "Wifi",
      "Essentials",
      "Hair dryer",
      "Hangers",
      "Iron",
      "Kitchen",
      "Free street parking",
      "Heating"
    ],
    "price": 53,
    "minimum_nights_number": 2,
    "maximum_nights_number": 1125,
    "instant_bookable": "FALSE"
  },
  {
    "name": "Domus Aventino Luxury Suite Apartment",
    "host_since": "19/01/2014",
    "host_location": "Italy",
    "host_response_time": "within a day",
    "host_response_rate": 0.27,
    "host_acceptance_rate": 0.09,
    "neighbourhood": "I Centro Storico",
    "city": "Rome",
    "latitude": 41.88015,
    "longitude": 12.48333,
    "property_type": "Entire apartment",
    "room_type": "Entire place",
    "guest_number": 3,
    "bedroom_number": 1,
    "amenities_list": [
      "Gym",
      "Oven",
      "Elevator",
      "Washer",
      "TV",
      "Dedicated workspace",
      "Private entrance",
      "Long term stays allowed",
      "Hangers",
      "Essentials",
      "Hair dryer",
      "Smoke alarm",
      "Air conditioning",
      "First aid kit",
      "Hot water",
      "Carbon monoxide alarm",
      "Kitchen",
      "Heating"
    ],
    "price": 99,
    "minimum_nights_number": 1,
    "maximum_nights_number": 1125,
    "instant_bookable": "TRUE"
  }
];
//
function loadBackend_JMS_v2(app,db){
    
  // REDIRECT al portal de documentación
  app.get(API_BASE_JMS + "/docs", (req, res) => {
    res.redirect("https://documenter.getpostman.com/view/33042302/2sA35G53Hy");
  });

    // GET => Lista todos los datos
    // Permite establecer un periodo con from y to
    // Permite buscar por cualquier parametro con ?parametro=valor
    // Permite paginacion con limit y offset
    // Permite filtrar por un rango de precios con ?min_price=valor&max_price=valor
    // Permite filtrar por año (extraido de la fecha de registro del host) con ?year=valor
    // Método para manejar las solicitudes GET a la ruta raíz
    // Método para manejar las solicitudes GET a la ruta raíz
      // Método para manejar las solicitudes GET a la ruta raíz
      app.get(API_BASE_JMS + "/", (req, res) => {
        const { amenities_list, from, to, min_price, max_price, limit, offset, name, year, ...queryParams } = req.query;
    
        if (amenities_list !== undefined) {
            const amenitiesArray = amenities_list.split(',');
            queryParams.amenities_list = { $in: amenitiesArray };
        };
    
        if (name !== undefined) {
            const nameRegex = new RegExp(name, 'i');
            queryParams.name = nameRegex;
        };
    
        if (year !== undefined && /^\d{4}$/.test(year)) {
            const limitNum = parseInt(limit) || 10;
            const offsetNum = parseInt(offset) || 0;
            const yearRegex = new RegExp(`\\d{2}/\\d{2}/${year}`);
    
            db.find({ host_since: { $regex: yearRegex } })
                .skip(offsetNum)
                .limit(limitNum)
                .exec((err, listings) => {
                    if (err) {
                        res.status(500).send("Internal Error");
                    } else {
                        if (listings.length === 0) {
                            return res.status(404).send("[]");
                        } else {
                            const responseBody = listings.map((listing) => { 
                                delete listing._id; 
                                return listing; 
                            });
                            return res.status(200).send(responseBody);
                        }
                    }
                });
        } else if (from !== undefined && to !== undefined) {
            const fromYear = parseInt(from);
            const toYear = parseInt(to);
            if (isNaN(fromYear) || isNaN(toYear)) {
                return res.status(400).send("Invalid year format. Please provide valid year values.");
            }
    
            db.find({}, (err, listings) => {
                if (err) {
                    return res.status(500).send("Internal Server Error");
                } 
    
                const filteredListings = listings.filter(listing => {
                    const listingYear = new Date(listing.host_since).getFullYear();
                    return listingYear >= fromYear && listingYear <= toYear;
                });
    
                const hasOtherFilters = Object.keys(queryParams).length > 0;
    
                let paginatedListings = filteredListings;
                if (limit !== undefined) {
                    const limitNum = parseInt(limit);
                    if (offset !== undefined) {
                        const offsetNum = parseInt(offset);
                        paginatedListings = filteredListings.slice(offsetNum, offsetNum + limitNum);
                    } else {
                        paginatedListings = filteredListings.slice(0, limitNum);
                    }
                }
    
                if (filteredListings.length === 0 && !hasOtherFilters) {
                    return res.status(404).send("[]");
                }
    
                let responseBody = paginatedListings.map((listing) => {
                    delete listing._id;
                    return listing;
                });
    
                res.status(200).send(responseBody);
            });
        } else if (min_price !== undefined && max_price !== undefined) {
            if (isNaN(parseFloat(min_price)) || isNaN(parseFloat(max_price))) {
                return res.status(400).send("Bad Request. Please provide valid numerical values for min_price and max_price.");
            }
    
            db.find({ price: { $gte: parseFloat(min_price), $lte: parseFloat(max_price) }, ...queryParams })
                .exec((err, listings) => {
                    if (err) {
                        return res.status(500).send("Internal Server Error");
                    }
    
                    if (listings.length === 0) {
                        return res.status(404).send("[]");
                    }
    
                    let paginatedListings = listings;
                    if (limit !== undefined) {
                        const limitNum = parseInt(limit);
                        if (offset !== undefined) {
                            const offsetNum = parseInt(offset);
                            paginatedListings = listings.slice(offsetNum, offsetNum + limitNum);
                        } else {
                            paginatedListings = listings.slice(0, limitNum);
                        }
                    }
    
                    let responseBody = paginatedListings.map((listing) => {
                        delete listing._id;
                        return listing;
                    });
    
                    res.status(200).send(responseBody);
                });
        } else if (Object.keys(queryParams).length === 0) {
            db.find({}, handleDbResponse);
        } else {
            db.find(queryParams, handleDbResponse);
            if (queryParams.host_response_rate) queryParams.host_response_rate = parseFloat(queryParams.host_response_rate);
            if (queryParams.host_acceptance_rate) queryParams.host_acceptance_rate = parseFloat(queryParams.host_acceptance_rate);
            if (queryParams.latitude) queryParams.latitude = parseFloat(queryParams.latitude);
            if (queryParams.longitude) queryParams.longitude = parseFloat(queryParams.longitude);
            if (queryParams.guest_number) queryParams.guest_number = parseInt(queryParams.guest_number);
            if (queryParams.bedroom_number) queryParams.bedroom_number = parseInt(queryParams.bedroom_number);
            if (queryParams.price) queryParams.price = parseFloat(queryParams.price);
            if (queryParams.minimum_nights_number) queryParams.minimum_nights_number = parseInt(queryParams.minimum_nights_number);
            if (queryParams.maximum_nights_number) queryParams.maximum_nights_number = parseInt(queryParams.maximum_nights_number);
        }
    
        function handleDbResponse(err, listings) {
            if (err) {
                return res.status(500).send("Internal Server Error");
            }
    
            if (listings.length === 0) {
                return res.status(404).send("[]");
            }
    
            let paginatedListings = listings;
            if (limit !== undefined) {
                const limitNum = parseInt(limit);
                if (offset !== undefined) {
                    const offsetNum = parseInt(offset);
                    paginatedListings = listings.slice(offsetNum, offsetNum + limitNum);
                } else {
                    paginatedListings = listings.slice(0, limitNum);
                }
            }
    
            let responseBody = paginatedListings.map((listing) => {
                delete listing._id;
                return listing;
            });
    
            res.status(200).send(responseBody);
        }
    });
    

    // GET => loadInitialData (al hacer un GET cree 10 o más datos en el array de NodeJS si está vacío)
    app.get(API_BASE_JMS+"/loadInitialData",(req,res) => {
      db.find({},(err,listings) => {
        if(err){
          res.res.status(500).send("Internal Server Error");
        }; 
        if (listings.length === 0) {
          db.insert(initialData, (err,listings) =>{
            if(err){
              console.error("Error al insertar datos iniciales:", err);
              res.status(500).send("Internal Server Error");
            } else {
              console.log("Database is empty.");
              console.log("Adding initial data.");
              res.status(201).send("Data Created");
            }
          });
        } else {
          console.log("Database already contains data, initial data won't be loaded again.");
          res.status(200).send("Database already contains data, initial data won't be loaded again.");
        }
      }); 
    }),


    // GET => Buscar por latitude y longitude con paginación
    app.get(API_BASE_JMS + "/:latitude/:longitude", (req, res) => {
      const { latitude, longitude } = req.params;

      // Parsear las coordenadas a números flotantes
      const latitudeFloat = parseFloat(latitude);
      const longitudeFloat = parseFloat(longitude);

      // Parsear los parámetros de paginación
      const limit = parseInt(req.query.limit) || 10; // Valor predeterminado: 10
      const offset = parseInt(req.query.offset) || 0; // Valor predeterminado: 0

      // Buscar las listas que coincidan con las coordenadas
      db.find({ latitude: latitudeFloat, longitude: longitudeFloat })
          .limit(limit)
          .skip(offset)
          .exec((err, listings) => {
              if (err) {
                  res.status(500).send("Internal Error");
              } else {
                  if (listings.length === 0) {
                      res.status(404).send("[]");
                  } else {
                      // Eliminar el campo _id de cada resultado
                      const responseBody = listings.map(listing => {
                          delete listing._id;
                          return listing;
                      })[0];

                      // Devolver la lista de resultados
                      return res.status(200).send(responseBody);
                  }
              }
          });
    });


    // POST => Create a new listing
    app.post(API_BASE_JMS + "/", (req, res) => {
      const newData = req.body;
      const expectedFields = ["name", "host_since", "host_location", "host_response_time", "host_response_rate", "host_acceptance_rate", "neighbourhood", "city", "latitude", "longitude", "property_type", "room_type", "guest_number", "bedroom_number", "amenities_list", "price", "minimum_nights_number", "maximum_nights_number", "instant_bookable"];
  
      const validResponseTimes = ["within an hour", "within a few hours", "within a day", "a few days or more"];
  
      const receivedFields = Object.keys(newData);
      const isValidData = expectedFields.every(field => receivedFields.includes(field));
  
      if (!isValidData) {
          res.status(400).send("Bad Request, please provide valid data"); // Datos inválidos
      } else {
          // Verificar si ya existe un documento con el mismo cci en la base de datos
          db.findOne({ latitude: newData.latitude, longitude: newData.longitude }, (err, existingData) => {
              if (err) {
                  res.status(500).send("Internal Error"); // Error interno del servidor
              } else {
                  if (existingData) {
                      res.status(409).send("Conflict, data already exists");  //Datos existentes
                  } else {
                      // Verificar si el valor de host_response_time es válido
                      if (!validResponseTimes.includes(newData.host_response_time)) {
                          res.status(400).send("Bad Request, invalid host_response_time"); // host_response_time inválido
                      } else {
                          // Si no existe, insertar el nuevo documento
                          db.insert(newData, (err, insertedData) => {
                              if (err) {
                                  res.status(500).send("Internal Error"); // Error interno del servidor
                              } else {
                                  res.status(201).send("Created");
                              }
                          });
                      }
                  }
              }
          });
      }
    });
  

    // PUT => Can't update root directory
    app.put(API_BASE_JMS + "/", (req,res)=> {
      res.status(405).send("Method Not Allowed");
    }),

      // PUT => Update resource by latitude and longitude
    app.put(API_BASE_JMS + "/:latitude/:longitude", (req, res) => {
        const latitude = parseFloat(req.params.latitude);
        const longitude = parseFloat(req.params.longitude);
        let data = req.body;
  
        if (!data || Object.keys(data).length === 0 || data.latitude !== latitude || data.longitude !== longitude) {
          res.status(400).send("Bad Request, please provide valid data"); // Datos inválidos
        } else {
            db.update({ latitude: latitude, longitude: longitude }, data, { }, (err) => {
                if (err) {
                  res.status(500).send("Internal Error"); // Error interno del servidor
                }
                res.status(200).send("OK, data updated"); //Actualizacion correcta
            });
        }
    }),

    // DELETE => Delete all data
    app.delete(API_BASE_JMS + "/", (req, res) => {
      db.remove({}, { multi: true }, (err, numRemoved) => { // Borrar todo la base de datos
        if (err) {
          res.status(500).send("Internal Error"); // Error interno del servidor
            return;
        } else {
            if (numRemoved >= 1) {
                console.log("All data has been deleted");
                res.status(200).send("OK, All data has been deleted"); // Todos los datos han sido eliminados correctamente
            } else {
                console.log("No data found for deletion");
                res.status(204).send("Database is empty"); // No se encontraron datos para eliminar
            }
        }
    });
  }),

    // DELETE => Delete specific data by latitude and longitude
    app.delete(API_BASE_JMS + "/:latitude/:longitude", (req, res) => {
    const latitude = parseFloat(req.params.latitude);
    const longitude = parseFloat(req.params.longitude);

    // Eliminar el documento con la latitud y longitud especificadas de la base de datos
    db.remove({ latitude: latitude, longitude: longitude }, {}, (err, numRemoved) => {
        if (err) {
            res.status(500).send("Internal Error");
        } else if (numRemoved === 0) {
            // No se encontró ningún documento con la latitud y longitud especificadas, devolver un error 404 NOT FOUND
            res.status(204).send("Listing not found");
        } else {
            // Se eliminó correctamente el documento
            res.status(200).send("OK, listing deleted");
        }
    });
    }),

    // DELETE => Eliminar por rango de precios
    app.delete(API_BASE_JMS + "/price/:min/:max", (req, res) => {
      const minPrice = parseFloat(req.params.min);
      const maxPrice = parseFloat(req.params.max);

      // Eliminar todos los documentos cuyo precio esté dentro del rango especificado
      db.remove({ price: { $gte: minPrice, $lte: maxPrice } }, { multi: true }, (err, numRemoved) => {
          if (err) {
              res.status(500).send("Internal Error");
          } else if (numRemoved === 0) {
              res.status(204).send("No content found");
          } else {
              res.status(200).send("OK, listing(s) deleted");
          }
      });
    }),

    // POST => Method not allowed
    app.post(API_BASE_JMS + "/:id", (req, res) => {
    // Devuelve un estado 405 (Método no permitido) con un mensaje explicativo
    res.status(405).send("METHOD NOT ALLOWED. Please use this endpoint to create a new resource without specifying an ID or param.");
    });
};

export {loadBackend_JMS_v2};