name: CI / CD
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies for front-end
        run: cd front && npm install && cd ..

      - name: Build front-end
        run: cd front && npm run build && cd ..

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright & Jest
        run: npx playwright install --with-deps && npm install --save-dev jest @playwright/test jest-playwright-preset

      - name: Run tests
        run: npm test  

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: gti-sos/SOS2324-12         

  deploy:
    needs: [test]   
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - run: npm install --save @fortawesome/free-solid-svg-icons
      - run: cd front && npm install --save @fortawesome/free-solid-svg-icons && npm install && npm run build && cd ..
    
      - name: Deploy
        run: gcloud app deploy