name: CI / CD
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd front && npm install && cd ..
      - run: cd front && npm run build && cd ..
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm i --save-dev @types/jest
      - run: npm test
  
  deploy:
    needs: [test]   
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - run: npm install --save @fortawesome/free-solid-svg-icons
      - run: cd front && npm install --save @fortawesome/free-solid-svg-icons && npm install && npm run build && cd ..
    
      - name: Deploy
        run: gcloud app deploy
